language: objective-c

os:
 - osx

cache:
 - apt
 - bundler

before_install:
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - ifmac brew install cmake || true
 - iflin sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - iflin sudo add-apt-repository -y ppa:andykimpe/cmake  # backport of cmake 2.8.12
 - iflin sudo add-apt-repository -y ppa:ondrej/php5 # libicu-dev 52
 - iflin sudo apt-get update
 - iflin sudo apt-get install libicu-dev=52.1-1+debphp.org~precise+1 gcc-4.7 g++-4.7 aptitude build-essential libfftw3-dev libxt-dev pkg-config cmake=2.8.12.2-3 libstdc++5
 - iflin sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
 - iflin sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
 - iflin sudo update-alternatives --auto gcc
 - git clone https://github.com/supercollider/supercollider.git

before_script:
 - mkdir BUILD
 - cd BUILD
 - cmake -DCMAKE_INSTALL_PREFIX:PATH=$PWD/SC3plugins -DCMAKE_BUILD_TYPE=Release -DSC_PATH=../supercollider ..

script:
 - make install
 - ifmac mkdir -p $HOME/artifacts
 - ifmac zip -r $HOME/artifacts/Plugins-$TRAVIS_COMMIT.zip SC3plugins

before_deploy:
 # required for github releases
 - git fetch --tags
 - export BUILD_PREFIX=$TRAVIS_REPO_SLUG/$TRAVIS_OS_NAME
 - export FWD_HTML='<html><head><meta http-equiv="refresh" content="0; url=Plugins-'$TRAVIS_COMMIT'.zip" /></head></html>'
 # put everything to be archived in artifacts/
 - mkdir -p "$HOME/artifacts/${TRAVIS_BRANCH%/*}"
 - mkdir -p "$HOME/artifacts/${TRAVIS_TAG%/*}"
 - echo $FWD_HTML > $HOME/artifacts/$TRAVIS_BRANCH-latest.html
 - 'if [[ $TRAVIS_TAG != "head" ]]; then echo $FWD_HTML > $HOME/artifacts/$TRAVIS_TAG.html; fi;'

deploy:
 # s3 upload - every commit
 - provider: s3
   access_key_id: $AWS_KEY
   secret_access_key: $AWS_SECRET
   bucket: supercollider
   local-dir: $HOME/artifacts
   upload-dir: builds/$BUILD_PREFIX
   region: us-west-2
   skip_cleanup: true
   endpoint: s3-us-west-2.amazonaws.com
   acl: public_read
   on:
     condition: $TRAVIS_OS_NAME = osx
     all_branches: true
# github releases - only tags
 - provider: releases
   api_key:
     secure: l2RJysBqtHTTi3qTVGXKCpsAkC/4evMukTsAmV9GSILdDuU1CMue1pSGpYqduQvKV3nn7UHClc3ah8yqRWn8xnSB8Eo9JX03dO8v29ury9F5FzceH0DARIB8iXMQXMM4MXm2R4xrGZDgLfwehr9PsXx/ZO90b24ffbEIY2Ji9nMOb9tGoPe4gUQo1DhsrBUInu+tKNJWS/1HfH2BrYRo4Y5EN1l/gx/LVjg7cWgeRS7BriBNAd1M1Qi7FmRKoknZPlrp6TOSjYZUaJEl/KMihdCrrKGQAxi9lEHCeVbTixMQwripId3c+tsC9tgIpQ0uBijdVR42J49xaGxJu03TaI8pL37kHvEZCVmFymwH5YIuoGdNLf9gaxOEBzeHmAxbZjnapAhHny4X9hT+DewgDb8o86eJ3ujTg6dDMHggjyrD1EdSHLnV0WDhJM8KpaozpIiR5XbIvalhUDFjQgsfeyYDp0FbioQgJUjWe8/JAkffqNibEjYdAs2ZngulM9B9QyeZpdFkR+ztz3Y1tCqKdz3XzD50Ai2/u4fVeB6qWL+HtDL1irZGG8lCwmNT8k/0u8d5yuEvA6qwv+Nw5jzvDqiq1VhTmxWJ8fOpYP4bsfG0EFrd9d8T7Bzdhi+IsV4daRLO21uFoHANG5kHKRWkApcmvzP3ts7N2WCgS/cC8nE=
   file: $HOME/artifacts/Plugins-$TRAVIS_COMMIT.zip
   prerelease: true
   skip_cleanup: true
   on:
     condition: $TRAVIS_OS_NAME = osx
     tags: true
     all_branches: true
notifications:
  on_success: change
  on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51b9b53ca50a7bfca97d
    on_success: change
    on_failure: always
